/**:
  navsat_transform:
    ros__parameters:
      world_frame: map
      broadcast_cartesian_transform: true
      frame_id: map
      broadcast_utm_transform: true
      broadcast_utm_transform_as_parent_frame: true
      frequency: 10.0
      delay: 3.0
      # Enter the magnetic declination for your location. If you don’t know it, see http://www.ngdc.noaa.gov/geomag-web (make sure to convert the value to radians). 
      #This parameter is needed if your IMU provides its orientation with respect to the magnetic north.
      magnetic_declination_radians: 0.0
      yaw_offset: 0.0
      zero_altitude: false
      publish_filtered_gps: false
      use_odometry_yaw: false
      wait_for_datum: false
      # datum: [51.708276, 5.299235, 0.0] # pre-set datum if needed, [lat, lon, alt] commented