services:
  common:
    volumes: 
      # Share X11 socket to allow GUI applications from the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Share X11 auth file so GUI works with the host X server
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    env_file:
      - .env
    privileged: true
    network_mode: host
    tty: true
    healthcheck:
      test:
        - CMD-SHELL
        - '[ -f /tmp/startup_complete ]'
      interval: 1s
      retries: 1000