x-common: &common
  volumes: 
    #- ..:/workspace:cached
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /mnt/wslg:/mnt/wslg
    - /root/.gazebo/models/:/root/.gazebo/models/
    - /var/run/docker.sock:/var/run/docker.sock 
    - $HOME/.Xauthority:/tmp/.Xauthority:rw
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/tmp/.Xauthority
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - CYCLONEDDS_URI=${CYCLONEDDS_URI}
  cap_add:
    - SYS_PTRACE
  command: /bin/sh -c "while sleep 1000; do :; done"
  privileged: true
  network_mode: "host"

services: 
  ros2-dev:
    <<: *common
    container_name: ros2-jazzy-dev
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
      target: dev

  ros2-go2:
    <<: *common
    container_name: ros2-go2-dev
    build:
      context: ../
      dockerfile: ./Docker/Dockerfile
      target: go2
