services: 
  sim-go2:
    extends:
      service: common
      file: ../docker-compose.common.yml
    container_name: sim-go2
    image: enexis/go2:latest
    command:
      - /bin/bash 
      - -c
      - ros2 launch enexis_go2 go2.launch.py use_sim_time:=True
  
  sim-localization:
    extends:
      service: common
      file: ../docker-compose.common.yml
    container_name: sim-localization
    image: enexis/go2:latest
    command:
      - /bin/bash 
      - -c
      - ros2 launch localization localization.launch.py start_ekf_local:=True use_sim_time:=True

  rviz:
    extends:
      service: common
      file: ../docker-compose.common.yml
    container_name: rviz
    image: enexis/dev:latest
    command:
      - /bin/bash
      - -c
      - ros2 run rviz2 rviz2 -d /workspace/src/platform_kits/enexis_go2/config/rviz.rviz --ros-args -p use_sim_time:=true

  gazebo:
    extends:
      service: common
      file: ../docker-compose.common.yml
    container_name: gazebo
    image: enexis/dev:latest
    command:
      - /bin/bash
      - -c
      - ros2 launch gazebo gazebo.launch.py world:=generated_world