services: 
  platform_kit:
    image: enexis/go2:latest
    build:
      context: ../../
      dockerfile: Docker/enexis_go2/Dockerfile
      target: go2
    extends:
      service: common
      file: ../docker-compose.common.yml
    healthcheck:
      test: ["CMD-SHELL", ". /opt/ros/jazzy/setup.sh && ros2 node list | grep -q /robot_state_publisher"]
      interval: 2s
      retries: 3
    command:
      - /bin/bash 
      - -c
      - ros2 launch enexis_go2 go2.launch.py use_sim_time:=True
  
  localization:
    image: enexis/go2:latest
    extends:
      service: common
      file: ../docker-compose.common.yml
    command:
      - /bin/bash 
      - -c
      - ros2 launch localization localization.launch.py use_sim_time:=True
  nav:
    image: enexis/go2:latest
    extends:
      service: common
      file: ../docker-compose.common.yml
    command:
      - /bin/bash 
      - -c
      - ros2 launch nav2 nav2.launch.py use_sim_time:=True

  rviz:
    image: enexis/dev:latest
    extends:
      service: common
      file: ../docker-compose.common.yml
    depends_on:
      gazebo:
        condition: service_healthy
    command:
      - /bin/bash
      - -c
      - ros2 run rviz2 rviz2 -d /workspace/src/platform_kits/enexis_go2/config/rviz.rviz --ros-args -p use_sim_time:=true

  gazebo:
    image: enexis/dev:latest
    extends:
      service: common
      file: ../docker-compose.common.yml
    restart: always
    healthcheck:
      test: ["CMD-SHELL", ". /opt/ros/jazzy/setup.sh && ros2 node list | grep -q /gzserver"]
      interval: 2s
      retries: 3
    command: ros2 launch gazebo gazebo.launch.py world:=generated_world
